import { Injectable } from '@nestjs/common';
import type { Prisma } from '../../generated/prisma/client.js';

export interface AuditEvent {
  action:
    | 'AUTH_LOGIN_SUCCEEDED'
    | 'AUTH_LOGOUT_SUCCEEDED'
    | 'DOCUMENT_CREATED'
    | 'DOCUMENT_UPDATED'
    | 'DOCUMENT_MOVED'
    | 'DOCUMENT_ARCHIVED'
    | 'DOCUMENT_RESTORED'
    | 'DOCUMENT_TRASHED'
    | 'DOCUMENT_RESTORED_FROM_TRASH'
    | 'DOCUMENT_PERMANENTLY_DELETED'
    | 'DOCUMENT_PREVIEWED'
    | 'DOCUMENT_DOWNLOADED'
    | 'DOCUMENT_EXTRACTION_CONFIRMED'
    | 'DOCUMENT_FOLDER_CREATED'
    | 'DOCUMENT_FOLDER_RENAMED'
    | 'DOCUMENT_FOLDER_MOVED'
    | 'DOCUMENT_FOLDER_DELETED'
    | 'TASK_CREATED'
    | 'TASK_UPDATED'
    | 'TASK_COMPLETED'
    | 'TASK_REOPENED'
    | 'TASK_CANCELLED'
    | 'TASK_ARCHIVED'
    | 'TASK_DOCUMENTS_CHANGED'
    | 'TASK_CATEGORY_CREATED'
    | 'TASK_CATEGORY_UPDATED'
    | 'TASK_CATEGORY_DELETED'
    | 'CALENDAR_EVENT_CREATED'
    | 'CALENDAR_EVENT_UPDATED'
    | 'CALENDAR_EVENT_CANCELLED'
    | 'CALENDAR_EVENT_DELETED'
    | 'CALENDAR_EVENTS_BULK_UPDATED'
    | 'CALENDAR_EVENTS_BULK_DELETED'
    | 'CALENDAR_TEMPLATE_CREATED'
    | 'CALENDAR_TEMPLATE_UPDATED'
    | 'CALENDAR_TEMPLATE_DELETED'
    | 'CALENDAR_TEMPLATE_APPLIED'
    | 'CALENDAR_TEMPLATE_BULK_APPLIED'
    | 'CALENDAR_TEMPLATE_BATCH_REVERTED'
    | 'SAVED_PLACE_CREATED'
    | 'CALENDAR_PREFERENCES_UPDATED'
    | 'CALENDAR_TRAVEL_PLAN_UPDATED'
    | 'CALENDAR_TRAVEL_PLAN_RECALCULATED'
    | 'TASK_SCHEDULED'
    | 'TASK_UNSCHEDULED'
    | 'FINANCIAL_ACCOUNT_CREATED'
    | 'FINANCIAL_ACCOUNT_UPDATED'
    | 'FINANCIAL_ACCOUNT_ARCHIVED'
    | 'FINANCIAL_ACCOUNT_RESTORED'
    | 'FINANCIAL_CATEGORY_CREATED'
    | 'FINANCIAL_CATEGORY_UPDATED'
    | 'FINANCIAL_CATEGORY_ARCHIVED'
    | 'RECOMMENDED_FINANCIAL_CATEGORIES_CREATED'
    | 'FINANCIAL_TRANSACTION_CREATED'
    | 'FINANCIAL_TRANSACTION_UPDATED'
    | 'FINANCIAL_TRANSACTION_DELETED'
    | 'FINANCIAL_TRANSACTION_DOCUMENTS_CHANGED'
    | 'FINANCIAL_TRANSFER_CREATED'
    | 'FINANCIAL_TRANSFER_UPDATED'
    | 'FINANCIAL_TRANSFER_DELETED'
    | 'FINANCE_IMPORT_CREATED'
    | 'FINANCE_IMPORT_CONFIGURED'
    | 'FINANCE_IMPORT_COMMITTED'
    | 'FINANCE_IMPORT_CANCELLED'
    | 'FINANCE_IMPORT_PROFILE_CREATED'
    | 'FINANCE_IMPORT_PROFILE_UPDATED'
    | 'FINANCE_IMPORT_PROFILE_DELETED'
    | 'FINANCE_CATEGORIZATION_RULE_CREATED'
    | 'FINANCE_CATEGORIZATION_RULE_UPDATED'
    | 'FINANCE_CATEGORIZATION_RULE_DELETED'
    | 'FINANCIAL_BUDGET_CREATED'
    | 'FINANCIAL_BUDGET_UPDATED'
    | 'FINANCIAL_BUDGET_ARCHIVED'
    | 'FINANCIAL_BUDGET_COPIED'
    | 'SPENDING_INSIGHT_ACKNOWLEDGED'
    | 'SPENDING_INSIGHT_DISMISSED'
    | 'RECURRING_EXPENSE_CONFIRMED'
    | 'RECURRING_CANDIDATE_DISMISSED'
    | 'RECURRING_EXPENSE_UPDATED'
    | 'RECURRING_EXPENSE_ARCHIVED'
    | 'BUCKET_LIST_CREATED'
    | 'BUCKET_LIST_UPDATED'
    | 'BUCKET_LIST_CLOSED'
    | 'BUCKET_LIST_ARCHIVED'
    | 'BUCKET_LIST_ITEM_CREATED'
    | 'BUCKET_LIST_ITEM_UPDATED'
    | 'BUCKET_LIST_ITEM_DELETED'
    | 'BUCKET_LIST_ITEM_COMPLETED'
    | 'BUCKET_LIST_ITEM_REOPENED'
    | 'BUCKET_LIST_ITEM_SKIPPED'
    | 'BUCKET_LIST_ITEM_RESTORED'
    | 'BUCKET_LIST_ITEM_PARTICIPANTS_CHANGED'
    | 'BUCKET_LIST_ITEM_DOCUMENTS_CHANGED'
    | 'BUCKET_LIST_ROLLOVER_COMPLETED';
  householdId?: string;
  userId?: string;
  entityType?: string;
  entityId?: string;
  metadata?: Prisma.InputJsonValue;
}

@Injectable()
export class AuditService {
  public async record(
    transaction: Prisma.TransactionClient,
    event: AuditEvent,
  ): Promise<void> {
    const data: Prisma.AuditLogUncheckedCreateInput = {
      action: event.action,
      ...(event.householdId ? { householdId: event.householdId } : {}),
      ...(event.userId ? { userId: event.userId } : {}),
      ...(event.entityType ? { entityType: event.entityType } : {}),
      ...(event.entityId ? { entityId: event.entityId } : {}),
      ...(event.metadata !== undefined ? { metadata: event.metadata } : {}),
    };
    await transaction.auditLog.create({ data });
  }
}
